### ISSUE TITLE
Bump supported svelte version to 4

### ISSUE THREAD

**Issue by nosovk** [Valexr/Slidy#111]
Could you please allow using Slidy with svelte4?
<img width="408" alt="image" src="https://github.com/Valexr/Slidy/assets/1398808/94546063-fcee-460e-8f1d-9ba7dbf57348">

**Comment by Valexr** [comment]
#111 merged

**Comment by Valexr** [comment]
Release needed?

**Comment by nosovk** [comment]
yep, needed

**Comment by Valexr** [comment]
Realised 👌🏻
