### ISSUE TITLE
build fails in sveltekit 2

### ISSUE THREAD

**Issue by nosovk** [Valexr/Slidy#113]
I've got an issue when try to use slidy in latest svelte kit.
Error looks like that:
<img width="691" alt="image" src="https://github.com/Valexr/Slidy/assets/1398808/b2a2c19d-13ef-4316-9c1b-3f561adbf47f">

[Once before,](https://github.com/basaran/svelte-recaptcha-v2/pull/18) I saw that there were changes in library format:
https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition
It could be that the same changes should be applied here also in both core and svelte package.

**Comment by Valexr** [comment]
🤔and css can't import `Missing "./dist/slidy.css" specifier in "@slidy/svelte" package`

**Comment by Valexr** [comment]
fixed & published @slidy/svelte@3.4.4

**Comment by Valexr** [comment]
please test it

**Comment by nosovk** [comment]
update helped, all works at sveltekit 2 now
