### ISSUE TITLE
Looping causes weird display issue and looping thumbnails

### ISSUE THREAD

**Issue by Loizzus** [Valexr/Slidy#132]
On Slidy Svelte I have an issue where when I set loop = true I am able to swipe the thumbnails. This also seems to cause the pictures to dissapear for a while and then display out of order. 

You can see the issue here on my test site: https://beta.obrien-group.co.nz/product/laminate

How it's supposed to look:
![image](https://github.com/user-attachments/assets/bc7d977e-a751-4751-82a6-e9cee7e53a03)

When the images dispear:
![image](https://github.com/user-attachments/assets/279c2e4a-8bca-4733-be11-023ac0d5cd86)

When the images do come back:
![image](https://github.com/user-attachments/assets/c2bf6506-7260-41e9-9739-e399cf7c7047)

The issue can be replicated just by fiddeling with it for a while. 

My slidy options are: 
```
	const slidyOptions = {
		clamp: 0,
		indent: 1,
		sensity: 2,
		gravity: 1,
		duration: 375,
		animation: stairs,
		easing: linear,
		snap: 'center',
		axis: 'x',
		loop: true,
		arrows: false,
		thumbnail: true,
		progress: false,
		navigation: false,
		counter: false,
    };
```

My markup:
```
	<div class="slidyContainer">
		<Slidy 
			bind:index={currentSlideIndex}
			{slides}
			{...slidyOptions}
			--slidy-height="500px"
		  />
		  <button on:click={() => {showProjectModal = true}}>See more {projectInfo[currentSlideIndex].name}</button>
	</div>
```

**Comment by Valexr** [comment]
https://github.com/user-attachments/assets/56a48829-d3da-4be0-b17d-c4eedc2137a9

Slidy in loop mode truly [swapping](https://github.com/Valexr/Slidy/blob/2f8c4cdd5d52bd78618ea966b9ff8493231e7e01/packages/core/src/lib/dom.ts#L79) DOMnodes by edges of carousel...

For right visual behavior slidy container needs to be wider then all carousel items...

https://github.com/user-attachments/assets/7107f02e-4ed5-4090-ba3f-53f793837c7f

**Comment by Valexr** [comment]
pretty furniture 👍🏻

**Comment by Loizzus** [comment]
Thanks, I'll give that a go on Monday 😊

**Comment by Valexr** [comment]
wrong info 😂 fix 
For right visual behavior slidy container needs to be NOT wider then all carousel items...

**Comment by Loizzus** [comment]
I tried setting --slidy-width="1000px" but the issue still occurred. I also tried adding .slidyContainer {width: 1000px;}

https://github.com/user-attachments/assets/7ad9a4ac-0c40-4b1c-a92a-584819c7fb06

Thanks for your help!

**Comment by Valexr** [comment]
Oh... I see the bug... needs time for testing

**Comment by Valexr** [comment]
reproduction [stend](https://svelte.dev/repl/de699aa1f8c04874b0402352ac93df96?version=4.2.19)

**Comment by Loizzus** [comment]
How do I get thumbs to stop scrolling?

**Comment by Valexr** [comment]
update your deps please & try again

**Comment by Valexr** [comment]
If slides width not wider container it's not scrolling ☝🏻

**Comment by Loizzus** [comment]
Hey, thank you so much for all your help. I've given it a go but I don't really know what I am supposed to put in the `<Core>` tag. The [documentation is a bit light](https://github.com/Valexr/slidy/tree/main/packages/svelte#core-component) on details. 

This is what I have tried:
```
<Core 
    bind:index={currentSlideIndex}
    {slides}
    {...slidyOptions}
    --slidy-height="500px"
>
        <img src={biancoLasa1}>
</Core>
```
@slidy_svelte.js?v=2888567e:489 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'call')
![image](https://github.com/user-attachments/assets/2253f6fd-7fb3-4970-9f99-930d7052d7d2)

![image](https://github.com/user-attachments/assets/4f42eafe-688a-406e-b964-bc5be05aae94)

**Comment by Valexr** [comment]
seems like this https://svelte.dev/repl/d8a7949b2acc4787be409124cd2b4440

**Comment by Valexr** [comment]
fixed 👌🏻update

**Comment by Loizzus** [comment]
Thank you that did fix the bug!

Now that I have core working (sort of) how do I do things such as set these flags? 
```
arrows: false,
thumbnail: true,
progress: false,
navigation: false,
counter: false,
```
![image](https://github.com/user-attachments/assets/e8ef07fb-86f2-4ecc-8338-3a406ce327cc)

Also the scrolling is now vertical, but maybe that's a CSS thing I can fix? :)

**Comment by Valexr** [comment]
1. The Core component haven't this flags
2. Use [REPL](https://svelte.dev/repl) to reproduce interactive examples for your questions. Maybe styles...🤷🏻‍♂️ `Core.svelte` component haven't any styles for this. 

[Core.svelte](https://github.com/Valexr/Slidy/tree/main/packages/svelte#core-component) component for fully custom templates - you need create styles, wrappers & navigation elements yourself.

**Comment by Loizzus** [comment]
Ok, I'm just going to go back to the original `<Slidy>` version I had working and not have looping then (`loop: false`).
