### ISSUE TITLE
immutable compiler option

### ISSUE THREAD

**Issue by nosovk** [Valexr/slidy#31]
Svelte provides some configuration options:
https://svelte.dev/docs#svelte_compile
```
compilerOptions: {
    immutable: true,
  },
```
setting immutable to true makes slidy broken.
<img width="419" alt="image" src="https://user-images.githubusercontent.com/1398808/145805369-13a77151-6476-4cd6-9d97-be5ca3d16bed.png">
it send us to https://github.com/Valexr/svelte-slidy/blob/master/src/Slidy.svelte#L254
Probably there is some problem in detecting options change.

**Comment by imhul** [comment]
+

**Comment by Valexr** [comment]
Tx for report🤓
I will look this in nearest time⏳

**Comment by Valexr** [comment]
fixed in v2.8.0 👌🏻

**Comment by Valexr** [comment]
Please check & report

**Comment by nosovk** [comment]
Will try it on stage now - https://mgf-stage.web.app/gudu/gudu-aw2122/gudu-aw2122-long-shirt-olive

**Comment by nosovk** [comment]
No more errors in console. Great!
I see that picture stopped updating on click, but I'm not sure that it's related to slider, will ask @imhul to check.
Thanks a lot.

**Comment by Valexr** [comment]
Check mobile resolution too😉& you can set options.sensity: Number - for responsiveness sliding

**Comment by Valexr** [comment]
Any question? Or I closed this?

**Comment by nosovk** [comment]
Yep, it seems that binded index property not updated now. Like we change index, but actual slide didn't change.

**Comment by nosovk** [comment]
<img width="260" alt="image" src="https://user-images.githubusercontent.com/1398808/146432192-ce42e586-bb22-42ea-9ba8-d1e09d4c6079.png">

**Comment by Valexr** [comment]
Don’t understand you… for examples see https://svelte.dev/repl/63eabf4de9ef40108da038cf55cba8dd

**Comment by Valexr** [comment]
Indexes - it’s true array[index]

**Comment by Valexr** [comment]
In `options.loop` mode you need await `bind:unit` for initialise index on mount… see repl example

**Comment by Valexr** [comment]
I hope for new year celebration I’m finished Slidy 3.0 - with full immutable logic, improve sliding behaviour & the same api… no external breaking changes… I hope 🤓

**Comment by Valexr** [comment]
Thumbnav example https://svelte.dev/repl/5979bd8521324a9b82a584521fbca6f9

**Comment by Valexr** [comment]
Sorry haven’t time for more readable docs 🤷🏻‍♂️But I hope rewrite it with 3.0 version 🤓

**Comment by nosovk** [comment]
https://svelte.dev/repl/036850d0abb9487e82f4523c23118711?version=3.44.3
probably it just not always updated, but problem with https://mgf-stage.web.app/gudu/gudu-aw2122/gudu-aw2122-long-shirt-olive somehow related to mutation of slides inside slidy

**Comment by Valexr** [comment]
What do you think about this realisation https://svelte.dev/repl/d33251a407df44b8ba48e93916b13588 like pluggable script to any nodes?

**Comment by Valexr** [comment]
can I close this issue? any other questions?

**Comment by nosovk** [comment]
yep, we currently disabled immutable for that one component. Will wait for v3.

**Comment by Valexr** [comment]
> yep, we currently disabled immutable for that one component. Will wait for v3.

3.0 in beta now in repository🤓
