### ISSUE TITLE
How to change slidy-dots color ??

### ISSUE THREAD

**Issue by hannapa1114** [Valexr/Slidy#32]
Hi, it really helpful to me. Thank you.

I want to change slidy-dots color!

In style, I use below code
```
<style>
	:global(.slidy-dots.pure li button) {
		background: lightskyblue;
	}
	:global(.slidy-dots.pure li.active button) {
		transform: scale(1.2);
		background: lightskyblue;
	}
</style>
```
but it doesn't work... help me!

**Comment by Valexr** [comment]
You need more specific selector by root wrapper id seems like `#slidy .slidy-dots.pure li button` - if don't change root id

**Comment by hannapa1114** [comment]
it works! thank you very much! God bless you!

**Comment by Valexr** [comment]
New version with acceleration, renderless & animation lifecycle (in future) coming soon 😉
https://svelte.dev/repl/d33251a407df44b8ba48e93916b13588

**Comment by EricRovell** [comment]
It is now available right now, but the `custom properties` API within new svelte template will solve this issue with ease. The [documentation](https://github.com/Valexr/Slidy/tree/master/packages/svelte#custom-properties-api) is available right now. Component can inherit custom properties to change the color of the dots. Hope you like it!

**Comment by rcapdepaula** [comment]
Nice!!

```
#slidy .slidy-dots.pure li button {
	color: lightblue;
}

#slidy .slidy-dots.pure li.active button {
	background-color: #49a7c2;
}
```
