### ISSUE TITLE
@slidy/svelte - Template props

### ISSUE THREAD

**Issue by Valexr** [Valexr/Slidy#38]
Needed simplify outside props configuration interface - like full object with `options` & like stand alone props...

**Comment by EricRovell** [comment]
Svelte template component props were reworked. No more objects, only individual props. It makes the API more elegant and solves a lot of problems with `immutable` mode and makes the component more performant, as object prop considered a bad practice for svelte components.

Ream more about current API [here](https://github.com/Valexr/Slidy/tree/master/packages/svelte#api).
