### ISSUE TITLE
@slidy/svelte - Styles Customisation

### ISSUE THREAD

**Issue by Valexr** [Valexr/Slidy#39]

**Comment by EricRovell** [comment]
Style customization is much more easier now. [Custom properties](https://github.com/Valexr/Slidy/tree/master/packages/svelte#custom-properties-api) are supported, and template nodes do not have hash on classes, specificity is not a problem anymore as we are not using native svelte `<style />` tag. Component and it's parts support passing down a `class` using `className` property.
