### ISSUE TITLE
@slidy/svelte - Disabled navigation arrows

### ISSUE THREAD

**Issue by Valexr** [Valexr/Slidy#55]
### Discussed in https://github.com/Valexr/Slidy/discussions/24

<div type='discussions-op-text'>

<sup>Originally posted by **tehnolog** April  6, 2021</sup>
Is there any way to show default (not external) arrows in "disabled" state? Arrows are being removed from DOM when slider reach start/end.

Maybe better solution is to add "disabled" attribute to the arrows and leave ability to hide them just with CSS.</div>

**Comment by EricRovell** [comment]
The problem solved in current svelte template. Disabled attribute is indeed a better solution, no layout shifts, more performant and accessible.
