### ISSUE TITLE
@slidy/core - prevent scroll axis crossing on touch/trackpad

### ISSUE THREAD

**Issue by inspiredlabs** [Valexr/Slidy#56]
With the new version of `slidy/core`, will it be possible to pass in `sensitivity` in `px`? 

In the previous version of slidy [you could pass in `sensity`](https://svelte.dev/repl/5c149e1aeef242bd889a7ecf115c02b5?version=3.46.4), which worked well enough, eg:

```
options: {
  sensity: 6.25, // lower number is more sensitive
}
```

Ideally you would pass in `96` to the vertical content wrapper to prevent a horizontal slide. This is especially useful with a mousewheel, or trackpad.

Thank you for Slidy btw. One day I hope it will compete with [Flickity](https://flickity.metafizzy.co/extras.html)!

**Comment by Valexr** [comment]
Thanks for regards @inspiredlabs, maybe 😁, but in bundle size `@slidy/core` wins of all carousel scripts now🤓

`sensity` props excluded from version 3. In core you have `gravity` & `duration` for kinetic tuning.
See in [example](https://svelte.dev/repl/8edad715f4054a20ac9b43af28b17083)
But haven't props for preventing from scroll crossing... okey will see ) maybe it will be default defending behaviour...🤔

And version @slidy/core without `indexer()`, `scroller()` function - this variables will passing through event `move` on scrollable/target node in function `slidy(node, options)`  in progress🚀

And version `@slidy/svelte@3.0` in progress now. All styles customisation through css vars & more...
Stay tune🤓

**Comment by Valexr** [comment]
@inspiredlabs & 1 more 😁in now development version `@slidy/core` allready preventing mouse wheel from scroll crossing

**Comment by Valexr** [comment]
@inspiredlabs fixed - now on wheel event with `vertical: false` preventing horizontal page scroll event (nav of browser history), but have free vertical scroll page. In `vertical: true` mode not preventing any default browser behavior. 
And with `e.shiftKey` both axis preventing default & Slidy sliding by indexes🤓

**Comment by inspiredlabs** [comment]
Brilliant, that was quick!

Please can you walk me through getting it to work on [this](https://github.com/inspiredlabs/offline/commit/cd4d36be3e592cdf93b3bdb633882575fd12781a) repo?

Here's what I've done:

- `npm i @slidy/core` in the project root following: https://www.npmjs.com/package/@slidy/core
- passed in `vertical: false,` to `<ul use:slidy={{ ... }}`.
- scrolled using the trackpad, see *screenshot*
- pushed it to [this](https://github.com/inspiredlabs/offline/commit/cd4d36be3e592cdf93b3bdb633882575fd12781a) repo.

![Screenshot 2022-02-25 at 12 14 49](https://user-images.githubusercontent.com/5474496/155706960-f182b21a-9f4d-4b76-a098-93e1e4875a5e.jpg)

**Comment by Valexr** [comment]
Fixed but not published - i'm working on global changes in new version 🤓sorry
What's yours problem?
