### ISSUE TITLE
@slidy/core: custom transitions

### ISSUE THREAD

**Issue by EricRovell** [Valexr/Slidy#61]
Right now the carousel does not support different transition. It might be very useful to have an option to pass a different transition options. I think it should be not just the parameters. The way `svelte` handles it would be perfect: some build-in transitions and the ability to pass custom ones.

[Web Animation API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Animations_API) could help us.

**Comment by Valexr** [comment]
The main feature of version 3 is to repeat the native scroll with the ability to index slides. But I agree - custom transitions are an interesting task. But I think not in this iteration. It would be nice to release first 😁

**Comment by EricRovell** [comment]
Yeah, I understand. I think implementing this correctly is not an easy task. I am sure users need it and will ask for it, so the issue should live and remind us of this feature :)

**Comment by Valexr** [comment]
Since v3.4.1 draft in the [@slidy/core](https://github.com/Valexr/Slidy/commit/61ee076c5e68b4e9e8688a9ba09e8727dc9f8982)
