### ISSUE TITLE
@slidy/core: items alignment

### ISSUE THREAD

**Issue by EricRovell** [Valexr/Slidy#64]
After some time I think I am completely sure: items alignment is a **must** option. Centring the carousel items is the most used case, still, there are some situations where you definitely need some other options.

**Comment by Valexr** [comment]
> After some time I think I am completely sure: items alignment is a **must** option. Centring the carousel items is the most used case, still, there are some situations where you definitely need some other options.

Return the `align` option?

**Comment by Valexr** [comment]
Returned https://github.com/Valexr/Slidy/commit/746250c9fc59759ee11c6d00dab7229f65c363bb

**Comment by EricRovell** [comment]
Thank you, I have updated the svelte template and demo, it works fine: 00b2a02b1fca6c589b15549639723b4f6b886f58.
