### ISSUE TITLE
@slidy/svelte - getImgSrc() in thumbs don't work

### ISSUE THREAD

**Issue by Valexr** [Valexr/Slidy#74]
Setting image link via `<Slidy getImgSrc={(item) => item.download_url} />` helper doesn't work for `thumbnail`.
[test](https://github.com/Valexr/Slidy/blob/ef00865ef4b2a2adec5ed2998b4bbedda6861f2a/www/src/routes/index.svelte#L56)

I'm not sure - maybe it must be separately for customisation images sizes in download links... 🤔

```svelte
<script>
  let img = {
    width: 500,
    height: 300
  },
  thumbs = {
    width: 100,
    height: 100
  }
  const url =  (item) => `https://api.photos.io/collection/12/${item.id}/${img.width}/${img.height}`
  const tumbUrl =  (item) => `https://api.photos.io/collection/12/${item.id}/${thumbs.width}/${thumbs.height}`
</script>

<Slidy 
  getImgSrc={ (item) => item.download_url = url} 
  thumbsSrc={ (thumb) =>  thumb.download_url = url } 
/>
```

**Comment by EricRovell** [comment]
Please, try `getThumbSrc` prop instead.
In case the thumbs are rendered and no `getThumbSrc` is provided, the `getImgSrc` is used for thumbs too.

**Comment by Valexr** [comment]
`getThumbSrc` is not provided & `getImgSrc` not work for thumbs...

why i write this? 😁

but if `getThumbSrc`defined  it's work... try dev:www

**Comment by Valexr** [comment]
(fixed)[https://github.com/Valexr/Slidy/commit/c86f65b87a1e4052404bde8ede05afdcd815e53f]
