### ISSUE TITLE
@slidy/svelte: autoplay

### ISSUE THREAD

**Issue by EricRovell** [Valexr/Slidy#76]
Tha `autoplay` feature was requested frequently while `slidy` was at v2.x.

As I see it, the feature should be implemented using these interface:

- `autoplay` - indicating the state;
- `interval` value in ms;

Also, there are more to consider:

- Should the `autoplay` stop on `hover` or `focus`?
- Should the `autoplay` stop at the end of the carousel?

For accessibility there should be a `pause` button too.

**Comment by Valexr** [comment]
Hover & focus stop will good optioned & stop by edges if not loop mode i think

**Comment by EricRovell** [comment]
Implemented `autoplay` feature. Not much configurable yet, still it works to accordance to accessibility guidelines.
