### ISSUE TITLE
@slidy/svelte: Arrows are not displayed in vertical direction when using axis="y"

### ISSUE THREAD

**Issue by yuan-kuan** [Valexr/Slidy#80]
Hello!

I just started using Slidy and found this issue in version 3.1.0.

This might be a mistake in: https://github.com/Valexr/Slidy/blob/c03d18109a18e2ce148a4ec90b66e53b0f71860e/packages/svelte/src/components/Arrow/arrow.module.css#L54

where the 

```
.slidy-arrow.prev.vertical slidy-arrow-icon {
``` 

should be 

```
.slidy-arrow.prev.vertical .slidy-arrow-icon {
```

I tested this fix by changing the node-modules's `slidy.css` directly. So, this might not be the correct fix.

**Comment by EricRovell** [comment]
Thank you, I will investigate this issue and handle it correctly soon.

**Comment by EricRovell** [comment]
@yuan-kuan fixed this issue within cd71fef, thank you.

**Comment by yuan-kuan** [comment]
Hey @EricRovell, thank you for the quick fix. 

I'm afraid we need to fix the "next" arrow too, which is line 58 on the same file. Sorry I didn't mention that in my comment.

**Comment by yuan-kuan** [comment]
Thank you for the quick fix!
