### ISSUE TITLE
@slidy/svelte: Overlay example is wrong in README

### ISSUE THREAD

**Issue by yuan-kuan** [Valexr/Slidy#81]
Hello!

I faced an issue adding an overlay to my Slidy and realised it was a mistake in the README's overlay section.

Referring to this line:
https://github.com/Valexr/Slidy/blob/4af649490ea27f40a1d0cf165600c8db28b37564/packages/svelte/README.md?plain=1#L299

The sample code is:

```
<Slidy>
	<slot name="overlay">
		<button> Share </button>
	</slot>
</Slidy>
```

Above is how a Svelte component supposes to support a named slot. Not how a user makes use of the named slot. The following works for me:

```
<Slidy>
	<button slot="overlay"> Share </button>
</Slidy>
```

I referred to Svelte tutorial here: https://svelte.dev/tutorial/named-slots

**Comment by EricRovell** [comment]
Thank you, I will investigate this issue and handle it correctly soon.

**Comment by EricRovell** [comment]
@yuan-kuan thank you for the issue. Indeed, that was inccorect.
The correct way to use `overlay` is to use (`<svelte:fragment />`)[https://svelte.dev/docs#template-syntax-svelte-fragment]:

```svelte
<Slidy>
	<svelte:fragment slot="overlay">
		<button> Share </button>
	</svelte:fragment>
</Slidy>
```

I have updated the docs.

**Comment by yuan-kuan** [comment]
That's a much better solution. Thanks!
