### ISSUE TITLE
Unsnapped behaviour impossible in Loop mode?

### ISSUE THREAD

**Issue by elron** [Valexr/Slidy#86]
I try to make a loop without snap but it enforces `snap` even that its set to `false`.
[Repo to reproduce](https://svelte.dev/repl/32df2e3773b04101b1d436b664a9252e?version=3.50.0)

**Comment by Valexr** [comment]
Yep… by default `loop` under the hood snapped by `center`…

**Comment by elron** [comment]
I see
Is there a way to override this?

**Comment by Valexr** [comment]
Now it’s impossible… loop it’s not easy case… Slidy are really shuffle Dom nodes - like carousel… & it requires surgical accuracy 🤓

**Comment by Valexr** [comment]
I think about free loop mode… not correct issue header 😁loop working but impossible unsnapped behaviour ✌🏻

**Comment by elron** [comment]
Yes, free loop mode is the correct header

**Comment by Valexr** [comment]
fixed https://github.com/Valexr/Slidy/commit/49a730394f0d8040e9bb19d792b23c0553555a1d
& will be realesed in 3.6.1
