### ISSUE TITLE
@slidy/svelte - rewrite autoplay based on play() plugin

### ISSUE THREAD

**Issue by Valexr** [Valexr/Slidy#91]
[play() plugin](https://github.com/Valexr/Slidy/blob/master/packages/plugins/src/lib/play.ts)

**Comment by yhdgms1** [comment]
The autoplay plugin now goes separately from @slidy/svelte. It is available [here](https://github.com/Valexr/Slidy/tree/master/packages/plugins/src/lib/autoplay)
