### ISSUE TITLE
repl for @slidy/core is down

### ISSUE THREAD

**Issue by nosovk** [Valexr/Slidy#98]
this repl: https://svelte.dev/repl/e7a3683b13b342dc8ecfc1d9b2b806f6
from @svelte/core readme: https://github.com/Valexr/Slidy/blob/main/packages/core/README.MD
is currently going to 404 page.
It would be nice to have some REPL with core package.

**Comment by Valexr** [comment]
TX for report @nosovk ✌🏻fixed https://github.com/Valexr/Slidy/commit/5ba859797450dc7f5787241575831a051900d923
